version: '3.8'

services:
    EcommerceWeb:
        build:
            context: .
            dockerfile: EcommerceWeb/Dockerfile
        container_name: EcommerceWeb_container
        ports:
            - "60:8080"
            - "61:8081"
        depends_on:
            - sqlserver
        networks:
            - sql_shared_network
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EcommerceDb;Persist Security Info=False;User ID=sa;Password=EcommerceDb@DevelopmentAdmin1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
    

    EcommerceApi:
        build:
            context: .
            dockerfile: EcommerceApi/Dockerfile
        container_name: EcommerceApi_container
        ports:
            - "62:8080"
            - "63:8081"
        depends_on:
            - sqlserver
        networks:
            - sql_shared_network
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EcommerceDb;Persist Security Info=False;User ID=sa;Password=EcommerceDb@DevelopmentAdmin1;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
    

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sql_server_container
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=EcommerceDb@DevelopmentAdmin1
        ports:
          - "1433:1433"
        networks:
          - sql_shared_network
        volumes:
          - sql_data:/var/opt/mssql

    papercut:
        image: jijiechen/papercut
        container_name: papercut
        ports:
          - "37408:37408"  # Web UI
          - "2525:25"      # Use 2525 externally -> 25 internally
        networks:
          - sql_shared_network
        restart: unless-stopped

volumes:
  sql_data:

networks:
  sql_shared_network:
